### ISSUE TITLE
Configuring is cumbersome 

### ISSUE THREAD

**Issue by guignont** [arcaneframework/sharc#9]
Hello,
Configuring Sharc is cumbersome:

cmake .... -DArccon_DIR=/my/path/to/Arcane.framework/install/share/cmake/Arccon -DAxlstar_DIR=/my/path/to/Arcane.framework/install/share/cmake/Axlstar -DAlienProd_DIR=/my/path/to/Alien.legacy_plugins/install/lib/cmake -DArcane_DIR=/my/path/to/Arcane.framework/install/lib/cmake/Arcane -DAlienPath=/my/path/to/Alien.legacy_plugins/install/ -DArccore_DIR=/my/path/to/Arcane.framework/install/lib/cmake/Arccore

may put off people curious about testing sharc.
Also it's strange to have 2 variables for alien:
-DAlienProd_DIR=/my/path/to/Alien.legacy_plugins/install/lib/cmake 
-DAlienPath=/my/path/to/Alien.legacy_plugins/install/

When all packages where built simultaneously via framework I suggest:
cmake ... -DArcaneFramework_DIR=/my/path/to/Arcane.framework

A+
Thomas

**Comment by guignont** [comment]
Hello, 
Using -DCMAKE_PREFIX_PATH=/my/path/to/Arcane.framework does not work. It seems that CMAKE_PREFIX_PATH must include all the paths  specified with the xxxx_DIR variables which does not help making configure more easy.

A+
Thomas

**Comment by grospelliergilles** [comment]
No. All the packages installed inside ArcaneFramework should be automatically found using only one `CMAKE_PREFIX_PATH`. CMake use the following paths to find packages : https://cmake.org/cmake/help/latest/command/find_package.html#id9.

All the packages config file are installed under `<prefix>/lib/cmake`.

**Comment by guignont** [comment]
Ok, I understand that there is no will to improve configuring procedure for sharc.

**Comment by grospelliergilles** [comment]
No.  I think we can improve configuration of `sharc` but for your specific issue using only `CMAKE_PREFIX_PATH` should work. I am not able to reproduce your problem because `sharc` only compile on `RedHat` environment and I only have an `ubuntu` machine. When `sharc` will compile on `ubuntu` we can look back to improve build configuration

**Comment by stdcm** [comment]
No worry, ShArc will be very soon configured only by a single  -DCMAKE_PREFIX_PATH=/my/path/to/Arcane.framework. The current limitation does not come from framework but from ShArc buildsystem. ShArc buidsystem will soon be replaced by  [app_buildsystem_tools](https://github.com/arcaneframework/app_buildsystem_tools) to solve this issue.
